export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const FETCH_CHAT_HISTORY_REQUEST = 'FETCH_CHAT_HISTORY_REQUEST';
export const FETCH_CHAT_HISTORY_SUCCESS = 'FETCH_CHAT_HISTORY_SUCCESS';
export const FETCH_CHAT_HISTORY_FAIL = 'FETCH_CHAT_HISTORY_FAIL';

export const RESET_CHAT_HISTORY = 'RESET_CHAT_HISTORY';